---
title:               Tad Glines
tagline:             Just another blog.
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "username" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "password" %>
name:                Tad Glines
twitter:             tadglines
github:              tadglines
email:               tad.glines@gmail.com
google_analytics_id: YOUR_GA_ID
disqus_shortname:    <%= ENV.fetch("disqus_shortname") { "" } %>
